name: Deploy on server

on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  build:
    name: Build bot image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build -t dax0d/formula_now:${{ vars.version }} .
    - name: Login to DH
      run: dokcer login -u dax0d -p ${{ secrets.DH_PASSWORD }}
    - name: Push image to DH
      run: docker push dax0d/formula_now:${{ vars.version }}
