name: Deploy on server

on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  build:
    name: Build bot image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build -t dax0d/formula_now:${{ vars.version }} .
    - name: Login to DH
      run: docker login -u dax0d -p ${{ secrets.DH_PASSWORD }}
    - name: Push image to DH
      run: docker push dax0d/formula_now:${{ vars.version }}
  run-on-server:
    name: Run container on the server
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Setup SSH key
      run: |
        mkdir ~/.ssh
        echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    - name: Connect to server
      run: ssh -i ~/.ssh/id_ed25519 root@${{ secrets.SERVER_IP }}
    - name: Pull image
      run: docker pull dax0d/formula_now:${{ vars.version }}
    - name: Stop current container
      run: docker stop formula_now
    - name: Delete current container
      run: docker rm formula_now
    - name: Run new contianer
      run: docker run -d -e TOKEN=${{ secrets.TOKEN }} ADMIN_ID=${{ secrets.ADMIN_ID }} dax0d/formula_now:${{ vars.version }}
