name: Test on push

on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  test:
    name: Test changes
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Instal dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python3 test.py -v
    - name: Run test again
      run: python3 test.py -v
