name: Test on push

on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  test:
    name: Test changes
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
        cache: pip
    - name: Instal dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python3 test.py -v
    - name: Run test again
      run: python3 test.py -v
